function kstar=berk(yts,penalty,kmax,kmin);
nt=rows(yts);
min=9999999999;
tau=zeros(kmax,1);
s2e=999*ones(kmax,1);

yt=yts;
reg=[];
for i=1:kmax;
reg=[reg lagn(yt,i)];
end;
yt0=yt;
reg0=reg;
yt0=trimr(yt,kmax+1,0);
reg0=trimr(reg,kmax+1,0);
sumy=sum(reg0(:,1).*reg0(:,1));
nef=nt-kmax-1;
for k=kmin:kmax;
b=myols(yt0,reg0(:,1:k));
e=yt0-reg0(:,1:k)*b;
s2e(k)=e'*e/nef;
tau(k)=(sum(b)*sum(b))*sumy/s2e(k);
end;
kk=seqa(1,1,kmax);
if penalty == 0;
mic=log(s2e)+2.0*(kk+tau)./nef;
else;
mic=log(s2e)+log(nef)*(kk)./nef;
end;
kstar=minindc(mic);
