function [ff,pp] = solve(aa,bb,cc,dd,phi,nk);
global lambda;
%
% Written by Paul Klein. Last modified 25 March 1998. 
%
% Format: [ff,pp] = solve(aa,bb,cc,dd,phi,nk)
%
% The meaning of these symbols is explained below.
%
% Suppose you have the system
%
% aa*E[x(t+1)|F(t)]+bb*x(t)+cc*E[z(t+1)|F(t)]+dd*z(t) = 0
%
% where z has the dynamics
%
% z(t+1)=phi*z(t)+eps(t+1)
%
% Partition x(t)=[d(t)' k(t)']' and let k(t) be predetermined (have zero
% one-period-ahead expectations error).
%
% We assume that eps is an exogenous white noise process and F is the 
% filtration generated by eps, k0 and z0.
%
% Note that k0 and z0 are exogenously given, but that d0 is determined
% endogenously (so as to ensure stability).
%
% Note that nk is the dimension of k(t).
%
% Let w(t) = [k(t)' z(t)']
%
% Then this function delivers the matrices ff and pp in the following 
% representation of the unique stable solution (supposing there is one).
%
% d(t)   = ff*w(t)
%
% w(t+1) = pp*w(t) + [0' eps(t+1)']'

nx = size(aa,1);
nz = size(phi,1);

dd=-dd;
bb=-bb;

aa = [aa,cc;zeros(nz,nx),eye(nz)];
bb = [bb,dd;zeros(nz,nx),phi];

nw = nk+nz;
nx = nx+nz;
nd = nx-nw;

% Doing the generalized Schur decomposition 

[t,s,z,q] = qz(bb',aa');
[s,t,z,q] = reorder(s,t,z,q);
s = s';
t = t';
zh = z';


% Checking whether the no of unstable eigenvalues is equal to nd

if ~((abs(s(nd,nd))<abs(t(nd,nd)))&(abs(s(nd+1,nd+1))>abs(t(nd+1,nd+1))));
   warning('Wrong number of stable eigenvalues.');
end

lambda = [diag(s) diag(t)];

% At this stage we have q'a = sz and q'b = tz where q and z are unitary, 
% s and t are lower triangular and the pairs (s(i,i),t(i,i)) are 
% ordered by descending modulus.

zh12  = zh(1:nd,nd+1:nx);
zh22  = zh(nd+1:nx,nd+1:nx);

% Checking whether zh22 is invertible %

if rcond(zh22)<=eps;
error('Invertibility condition violated')
end

zh22i = zh22\eye(nw);
s22  = s(nd+1:nx,nd+1:nx);
t22  = t(nd+1:nx,nd+1:nx);
dyn = s22\t22;

ff  = zh12*zh22i;
pp  = zh22*dyn*zh22i;
